console.log(2>1);

console.log("\n");

console.log("2">1);
console.log("01">=1);
console.log("01">"1");
console.log("abc">"ab");
console.log("abc"<"ab");
console.log("2"<"12");
console.log("2"<12);
console.log("apple"<"banana");
console.log("apple">"banana");
console.log("\n");
console.log(undefined==null);
console.log(undefined===null);
console.log(undefined!=null);
console.log(undefined!==null);
console.log("\n");
console.log(0==false);
console.log(0===false);
console.log(0!=false);
console.log(0!==false);
console.log("\n");
console.log("0"==false);
console.log("0"===false);
console.log("0"!=false);
console.log("0"!==false);
console.log("\n");
console.log(""==false);
console.log(""===false);
console.log(""!=false);
console.log(""!==false);
console.log("\n");
console.log(" \t\n"==false);
console.log(" \t\n"===false);
console.log(" \t\n"!=false);
console.log(" \t\n"!==false);
console.log("\n");
console.log(null==false);
console.log(null===false);
console.log(null!=false);
console.log(null!==false);
console.log("\n");
console.log(undefined==false);
console.log(undefined===false);
console.log(undefined!=false);
console.log(undefined!==false);
console.log("\n");
console.log(NaN==NaN);
console.log(NaN===NaN);
console.log(NaN!=NaN);
console.log(NaN!==NaN);
console.log("\n");
console.log(Infinity>Infinity);
console.log(Infinity===Infinity);
console.log(-Infinity<-Infinity);
console.log(-Infinity===-Infinity);
console.log("\n");
console.log(0 == null);
console.log(0 === null);
console.log(0 != null);
console.log(0 !== null);
console.log("0"==null);


